BaseUrl= "https://mbahack2.syui.cf/hugo-theme-air/"
LanguageCode= "en-US"
Title= "Hugo Theme Air"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true

[author]
  name = "Daniel Vidali Fryer"

[params]
  description = "by Daniel V Fryer"
  cover = "images/user.jpg"
  author = "Daniel Vidali Fryer"
  authorlocation = "Melbourne, Australia"
  authorwebsite = "https://github.com/frycast"
  bio= "Statistical Machine Learning PhD student at The University of Queensland"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "syui"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
